apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: us-central1-docker.pkg.dev/black-anagram-431013-u8/docker-repository/myapp:1.0.0
          ports:
            - containerPort: 3000
