apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: us-central1-docker.pkg.dev/your-project-id/black-anagram-431013-u8/sample-app:1.0.0
          ports:
            - containerPort: 3000
