apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: sample-app
          image: us-central1-docker.pkg.dev/black-anagram-431013-u8/docker-repository/hello-app:v1
          ports:
            - containerPort: 3000
