apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
