apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: nginx-port
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: myapp
